sudo: required
dist: trusty
language: node_js
node_js:
  - '9.0'

addons:
apt:
  packages:
    - python3

cache:
  directories:
  - node_modules
  - bins

before_script:
  - cd ./bins/particl-core
  - wget https://github.com/particl/particl-core/releases/download/v0.18.0.5rc1/particl-0.18.0.5-x86_64-linux-gnu.tar.gz
  - tar -xvf particl-0.18.0.5-x86_64-linux-gnu.tar.gz
  - cd ../..
  - yarn install

script: 
  # download binaries
  - PARTICL_BINDIR=./bins/particl-core/particl-0.18.0.5/bin/ python3 particl-test-env.py &
  - sleep 20
  - yarn run test