sudo: required
dist: trusty
language: node_js
node_js:
  - '9.0'

addons:
apt:
  packages:
    - python3

cache:
  directories:
  - node_modules
  - bins

before_script:
  - yarn install

script: 
  # download binaries
  - python3 particl-test-env.py &
  - sleep 20
  - yarn run test
